### ISSUE TITLE
[Suggestion] Config line to disable the tooltip

### ISSUE THREAD

**Issue by Desempregago** [Minenash/walk-jog-run#1]
![image](https://user-images.githubusercontent.com/14002834/190871243-9b73d33f-fc85-4972-9986-c730ab7d8954.png)

**Comment by Desempregago** [comment]
Since there's an icon for each "speed" (walking > jogging > sprinting), the tooltip can be optionally removed

**Comment by Minenash** [comment]
I actually meant to remove it all together, yeah, i can push an update

**Comment by Minenash** [comment]
Sorry it took so long, update has been pushed
