### ISSUE TITLE
incorrect icon position in creative mode

### ISSUE THREAD

**Issue by peow** [Minenash/walk-jog-run#10]
the icon is obstructing the view of the names of the items when you are in creative mode, it would be interesting if in creative the icon was slightly downwards, or simply have an option to disable it in creative

![image](https://github.com/Minenash/walk-jog-run/assets/105888751/7af5be2d-f54f-4abf-b8e5-55a4582266a0)

![image](https://github.com/Minenash/walk-jog-run/assets/105888751/9e25e417-9c03-4806-901a-b120ac5f7c2c)

- im using the **Icon Position - Above Hotbar** config option

**Comment by Minenash** [comment]
Fixed in v1.1.1
