### ISSUE TITLE
HUD Icon switches back to default position upon closing and reopening the game.

### ISSUE THREAD

**Issue by TheRebelT** [Minenash/walk-jog-run#2]
Every time I've opened up Minecraft and loaded into the same world, the HUD icon keeps switching back to the hotbar setting and I'm needing to switch it to the bottom left setting each time.

Steps to reproduce:
-Load up game, create a world
-Go into the mod settings and change the position to bottom left (haven't tested other positions)
-Close it, then save and quit. Close the game.
-Start Minecraft again, load up into the same world and the icon has returned back to the hotbar setting.

**Comment by TheRebelT** [comment]
Forgot to mention I am doing this through modmenu, I've not tried doing it through the file directly.

**Comment by Minenash** [comment]
I must've fixed it awhile ago but forgot to mention it here, since I can't recreate it in v1.0.2+1.20.3
