### ISSUE TITLE
0 Hunger makes stamina infinite

### ISSUE THREAD

**Issue by AfterRebelion** [Minenash/walk-jog-run#3]
Seems like a divide by 0 situation. 
When hunger bar is empty (0 hunger), the stamina never decreases, it stays always full.
You still receive the slowness effect, but only once. Once this effect fades off, you can run at normal running speed, forever.

**Comment by Minenash** [comment]
Fixed in [latest release](https://modrinth.com/mod/walk-jog-run/version)!
