### ISSUE TITLE
i have draw some pixel icons for ya

### ISSUE THREAD

**Issue by morrussa** [Minenash/walk-jog-run#4]
![sprinting](https://github.com/Minenash/walk-jog-run/assets/121374623/92e81fb6-4f0d-4ff6-ad05-73bf8448eb4e)
![strolling](https://github.com/Minenash/walk-jog-run/assets/121374623/7b26a96d-0325-4939-b7cb-cabc249f494c)
d 
![walking](https://github.com/Minenash/walk-jog-run/assets/121374623/a09ba07a-b159-48d4-a61f-3b01b72650e6)

**Comment by Minenash** [comment]
So sorry for not looking at this sooner. These do look good, and I'll include it in the next update!

**Comment by Minenash** [comment]
They are now in the [latest version](https://modrinth.com/mod/walk-jog-run/version)! Thanks again for these icons, and sorry again for it taking forever to be added
