### ISSUE TITLE
request: Push-to-Strolling hotkey

### ISSUE THREAD

**Issue by peow** [Minenash/walk-jog-run#6]
I'm using this mod because it's the only one I found that allows me to walk slower, but I'm having a problem, I find it annoying having to press the hotkey to enter Strolling mode, and press it again to exit, I believe it would be more interesting to have a function of Push-to-Strolling, where for example I would configure as the R key, so when I hold down the R key, I would walk slower, and as soon as I release the R key, I would go back to walking at normal speed

-------------

If it is possible to add this function, I ask you to update it to Fabric 1.20.1 with support to Fabric Loader 0.14.22, which is the version in which I am playing my modpack

**Comment by Minenash** [comment]
Added in [latest release](https://modrinth.com/mod/walk-jog-run/version).

Though this is for 1.20.3/4. It's been a few months since you asked for this, do you still use 1.20.1?

**Comment by peow** [comment]
thanks for adding the feature
yes i'm still using 1.20.1 because i've been making a modpack in this version for several months

**Comment by peow** [comment]
tysm for the 1.20.1 update, you're awesome
