### ISSUE TITLE
Request: Option to disable stamina system

### ISSUE THREAD

**Issue by frugbug** [Minenash/walk-jog-run#7]
I'm using this mod just for the ability to walk slower, and if possible, I'd love there to be an option to disable the stamina system, or give the player infinite stamina.

**Comment by peow** [comment]
try to use this in your config file:

  "STAMINA_DEPLETION_PER_TICK": 0,

**Comment by Minenash** [comment]
In version 1.1.0, I've also added a config option to disable the stamina system
