### ISSUE TITLE
Icon visibility config not working

### ISSUE THREAD

**Issue by layncemc** [Minenash/walk-jog-run#9]
In Fabric 1.20.1, changing the config for the icon visibility to false does not hide the status. Moving it to different locations on the screen seems to work just fine though, just toggling it on and off visually

**Comment by Minenash** [comment]
The setting is actually about showing the stamina using the icon, not if the icon is rendered (it's still useful for sprint/stroll/walk). Though, I can def add a position option that is none

**Comment by Minenash** [comment]
Added the None option in v1.1.1
